apiVersion: v1
kind: Service
metadata:
  name: rapidapp-service
  namespace: production
spec:
  selector:
    app: rapidapp
  type: NodePort
  ports:
  - port: 8000       # The port the service exposes internally
    targetPort: 8000  # The target port on the pods
    nodePort: 30001  # The port to expose on the EC2 instance's IP (choose an available port between 30000-32767)
